### ISSUE TITLE
Crashing, not sure why.

### ISSUE THREAD

**Issue by vVwd** [way2muchnoise/WAILA-features#13]
[Log](http://pastie.org/private/8qrftac8moktskcmrf4cg)

**Comment by way2muchnoise** [comment]
Could you provide a zip with the used mods? And please use a paste service([pastebin](http://pastebin.com/), [gist](https://gist.github.com/), [pastie](http://pastie.org/), ...) for logs.

**Comment by vVwd** [comment]
Sure, will do. Gimme a sec.

**Comment by vVwd** [comment]
http://pastebin.com/EC0SNvYZ -> complete log
https://mega.nz/#!koNDVZpB -> all mods

Weird side effect is that all mods remain loaded somehow. Have to restart laptop to be able to delete the mod from the mod folder. Forge is latest version, btw.

**Comment by way2muchnoise** [comment]
that mega link has some kind of encoding/password. Mind sharing or removing that?

**Comment by vVwd** [comment]
Never gave it a key or password. Must be a Mega protection thingy.

Does this work?

https://mega.nz/#!koNDVZpB!KC5JvjB2-O_4hxm8E4IZ8SwGuyOWbCDx1_zcUOw2ius

**Comment by way2muchnoise** [comment]
Yeah, that works investigating now

**Comment by vVwd** [comment]
Roger that. ;)

**Comment by way2muchnoise** [comment]
I have no real clue to why some mods id or meta data would be null. But now I check for it so it shouldn't happen again. A new alpha build will be up on curse as soon as the build server builds it and Curse approves it. (Should be in about 10 mins from this comment depending on how fast curse is)
