### ISSUE TITLE
Odd Nei Occurance

### ISSUE THREAD

**Issue by EndermanParty** [way2muchnoise/WAILA-features#2]
When I install your mod every item in the game bugs out and names itself "unnamed". Which in turn makes Nei unusable, I like this addon mod for Nei and I was hoping you'd be able to fix it or (if you already know how to) Tell me how to fix it..
Thank you for your time.

**Comment by way2muchnoise** [comment]
@EndermanParty Screeenshots, mod version, forge version. I need at least some of those to be actually able to get to the root of the problem

**Comment by way2muchnoise** [comment]
Closed due to no response
