### ISSUE TITLE
Nei search not function

### ISSUE THREAD

**Issue by skulldrago** [way2muchnoise/WAILA-features#3]
Your mod blocks the nei search. So i can´t search for my blocks and machines. After deleted your mod out of my mods folder i can search normally in nei. I play on Minecraft 1.7.10

**Comment by way2muchnoise** [comment]
@skulldrago Make sure the debug mode is off in the config and maybe activate the prefixes? That should disable the search filters without using the prefixes

**Comment by skulldrago** [comment]
Thank you i have tried it . The colour prefix option was false i have changed it to true and now the search is function normally.
