### ISSUE TITLE
Crash game

### ISSUE THREAD

**Issue by Tsyklop** [way2muchnoise/WAILA-features#5]
http://pastebin.com/CJAmCUHM

**Comment by way2muchnoise** [comment]
Could you provide some more information such as WAILA-features version (and WAILA version) and how to recreate the crash(or at least the conditions this happened in)

**Comment by Tsyklop** [comment]
WAILA-features-1.7.10-0.0.3, Waila-1.5.10_1.7.10.

I switched the two tabs mods in creative and crash

**Comment by spannerman79** [comment]
~~I was about to post the same issue - i found i had this issue with the Wrench and iWrench from [Funky Locomotion](http://minecraft.curseforge.com/mc-mods/224190-funky-locomotion)~~

I was using a more updated version - i'll create a new issue
