### ISSUE TITLE
Mod Compatibility: Funky Locomotion

### ISSUE THREAD

**Issue by spannerman79** [way2muchnoise/WAILA-features#6]
NotEnoughItems-1.7.10-1.0.5.111-universal
WAILA-features-1.7.10-0.0.4
funky-locomotion-1.7.10-beta-7
Waila-1.5.10_1.7.10
Forge: 1448

In NEI - mouseover either Wrench or iWrench and crash.

Crash log: http://paste.ee/p/qT3IX

Similar to #5

**Comment by mrammy** [comment]
confirmed https://github.com/way2muchnoise/WAILA-features/commit/cb947e1cbd477b665633dc339769835d3170b1b9 fixes this issue and likely #5
