### ISSUE TITLE
[Suggestion] see the author(s) of the mod - enable or disable in config file

### ISSUE THREAD

**Issue by Tsyklop** [way2muchnoise/WAILA-features#8]
Please add to configuration file to enable or disable this function.

**Comment by way2muchnoise** [comment]
Added them and made a build here and on CF. But out of curiosity what do you need the mod for if not the author feature? Or are you one of the few that use the search things? Cause nothing but hugs for you then. \o/

**Comment by Tsyklop** [comment]
author available by downloading the mod.
I do interfere ...

**Comment by way2muchnoise** [comment]
Uhmm I have no clue what you mean with your last comment
